import 'package:flutter/material.dart';

ThemeData lightTheme = ThemeData.light().copyWith(
  scaffoldBackgroundColor: Color(0xfff5ede0),
  textTheme: TextTheme(
    bodySmall: const TextStyle(
      fontSize: 12,
      fontFamily: 'Inter',

      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
      letterSpacing: 0.4,
      wordSpacing: 0.2,
      height: 1.4,

      color: Color(0xFF5F564B),
      decoration: TextDecoration.none,
      decorationColor: Color(0xFF666666),
      decorationThickness: 1.0,
      overflow: TextOverflow.visible,
    ),
    bodyMedium: const TextStyle(
      fontSize: 14,
      fontFamily: 'Inter',
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
      letterSpacing: 0.25,
      wordSpacing: 0.2,
      height: 1.5,
      color: Color(0xFF4A433A),
      decoration: TextDecoration.none,
      decorationColor: Color(0xFF666666),
      decorationThickness: 1.0,
      overflow: TextOverflow.visible,
    ),
    bodyLarge: const TextStyle(
      fontSize: 16,
      fontFamily: 'Inter',

      fontWeight: FontWeight.w500,
      fontStyle: FontStyle.normal,
      letterSpacing: 0.15,
      wordSpacing: 0.25,
      height: 1.5,
      color: Color(0xFF3A342C),
      decoration: TextDecoration.none,
      decorationColor: Color(0xFF666666),
      decorationThickness: 1.0,
      overflow: TextOverflow.visible,
    ),
    headlineSmall: const TextStyle(
      fontSize: 20,
      fontFamily: 'Poppins',

      fontWeight: FontWeight.w600,
      fontStyle: FontStyle.normal,
      letterSpacing: 0.0,
      wordSpacing: 0.0,
      height: 1.3,
      color: Color(0xFF2B2722),
      decoration: TextDecoration.none,
      decorationColor: Color(0xFF666666),
      decorationThickness: 1.0,
      overflow: TextOverflow.visible,
    ),
    headlineMedium: const TextStyle(
      fontSize: 24,
      fontFamily: 'Poppins',
      fontWeight: FontWeight.w700,
      fontStyle: FontStyle.normal,
      letterSpacing: 0.0,
      wordSpacing: 0.0,
      height: 1.25,
      color: Color(0xFF1F1B18),
      decoration: TextDecoration.none,
      decorationColor: Color(0xFF666666),
      decorationThickness: 1.0,
      overflow: TextOverflow.visible,
    ),
    headlineLarge: const TextStyle(
      fontSize: 30,
      fontFamily: 'Unbounded',
      fontWeight: FontWeight.w700,
      fontStyle: FontStyle.normal,
      letterSpacing: -0.25,
      wordSpacing: 0.0,
      height: 1.2,
      color: Color(0xFF181512),
      decoration: TextDecoration.none,
      decorationColor: Color(0xFF666666),
      decorationThickness: 1.0,
      overflow: TextOverflow.visible,
    ),
  ),

  floatingActionButtonTheme: FloatingActionButtonThemeData(
    sizeConstraints: const BoxConstraints(
      maxHeight: 60,
      minHeight: 59,
      maxWidth: 60,
      minWidth: 59,
    ),
    shape: const CircleBorder(),
    iconSize: 26,
    elevation: 0,
    backgroundColor: Color(0xffE95401),
  ),
);
